# Dockerfile

FROM docker.repository.cloudera.com/cdsw/engine:7
RUN pip3 install --upgrade pip
RUN pip3 install keras
RUN pip3 install tensorflow
RUN pip3 install sklearn
RUN pip3 install 'prompt-toolkit==1.0.15'
RUN pip3 install jupyter

